//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: CAITWinKinectController.idl
//  Source: CAITWinKinectController.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPCAIWINKINECTCONTROLLER_ICE
#define ROBOCOMPCAIWINKINECTCONTROLLER_ICE

module RoboCompCAIWinKinectController
{
	interface AgentToWinKinectController
	{
		void restartWinKinectComp();
	};
};

#endif
