//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: PersonSa3ir.idl
//  Source: PersonSa3ir.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPPERSONSA3IR_ICE
#define ROBOCOMPPERSONSA3IR_ICE

module RoboCompPersonSa3ir{
	interface PersonToAgent{
		void  peopleDetected(int npersons);
	};
};
  
#endif
